apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
    name: ui-vault
spec:
    selector:
        app: ui-vault
    ports:
        - protocol: "TCP"
          port: 8200 # The port that the service is running on in the cluster
          targetPort: 8200 # The port exposed by the service
          nodePort: 30090
    type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
    name: ui-vault
spec:
    selector:
        matchLabels:
            app: ui-vault
    replicas: 1 # Number of replicas that will be created for this deployment
    template:
        metadata:
            labels:
                app: ui-vault
        spec:
            containers:
                - name: ui-vault
                  image: ashwani13/uivault # Image that will be used inside the container in the cluster
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8200 # The port that the container is running on in the cluster
